logging:
  level:
    org:
      hibernate: INFO
      springframework:
        web: DEBUG
    root: warn
    
---
cognito:
  url: ${COGNITO_URL}
  key: ${COGNITO_KEY}

spring:
  profiles:
    active: ${DEPLOYMENT_STAGE}
  application:
    name: interview-service
  main:
    allow-bean-definition-overriding: true
  datasource:
   driver-class-name: org.h2.Driver
   platform: h2
   url: jdbc:h2:mem:testDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
   username: sa
   password:
 # datasource:
  #  driverClassName: org.postgresql.Driver
  #  initialization-mode: NEVER
  #  password: ${DB_PASSWORD}
  #  url: jdbc:postgresql://${DB_URL}:5432/postgres
  #  username: ${DB_USERNAME}
  h2:
    console:
      enabled: true 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  #  generate-ddl: false
  #  hibernate:
  #    ddl-auto: none
  #  properties:
  #    hibernate:
  #      default_schema: ${DB_SCHEMA}
    show-sql: false  

server:
  port: 8091

---
spring:
  profiles: dev



eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8888}/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
   
  